In [4]:
import pandas as pd
import datetime
import numpy as np
import statistics

In [5]:
df = pd.read_csv("weather_2012.csv")

In [6]:
#2 -- first 5 rows
df.head()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog

In [7]:
#2 -- random 5 rows
df.sample(5)

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
120,2012-01-06 00:00:00,-9.6,-16.8,56,13,25.0,100.81,Cloudy
1136,2012-02-17 08:00:00,2.8,-1.2,75,32,24.1,100.67,Cloudy
5963,2012-09-05 11:00:00,23.4,17.9,71,7,24.1,100.57,Rain Showers
7056,2012-10-21 00:00:00,9.2,6.3,82,13,25.0,100.07,Mainly Clear
5405,2012-08-13 05:00:00,19.5,17.5,88,13,24.1,100.78,Mainly Clear

In [8]:
#2 -- last 5 rows
df.tail()

,Date/Time,Temp (C),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [9]:
#3 -- column names
df.columns

Index(['Date/Time', 'Temp (C)', 'Dew Point Temp (C)', 'Rel Hum (%)',
       'Wind Spd (km/h)', 'Visibility (km)', 'Stn Press (kPa)', 'Weather'],
      dtype='object')

In [10]:
#4 -- new columns
col_names=['Date_Time', 'Temp_C',
'Dew_Point', 'Relative_Humidity', 'Wind_Speed', 'Visibility', 'Pressure', 'Weather']

#copy of original
original_cols = ['Date/Time', 'Temp (C)', 'Dew Point Temp (C)', 'Rel Hum (%)',
       'Wind Spd (km/h)', 'Visibility (km)', 'Stn Press (kPa)', 'Weather']

In [11]:
df.columns = col_names

In [12]:
df.sample()

,Date_Time,Temp_C,Dew_Point,Relative_Humidity,Wind_Speed,Visibility,Pressure,Weather
2569,2012-04-17 01:00:00,18.9,9.6,55,35,25.0,100.42,Mainly Clear

In [13]:
#5 -- general stats
round(df[["Temp_C", "Dew_Point", "Relative_Humidity", "Wind_Speed", "Visibility", "Pressure"]].mean(),4)

Temp_C                 8.7981
Dew_Point              2.5553
Relative_Humidity     67.4317
Wind_Speed            14.9455
Visibility            27.6644
Pressure             101.0516
dtype: float64

In [14]:
round(df[["Temp_C", "Dew_Point", "Relative_Humidity", "Wind_Speed", "Visibility", "Pressure"]].median(),4)

Temp_C                 9.30
Dew_Point              3.30
Relative_Humidity     68.00
Wind_Speed            13.00
Visibility            25.00
Pressure             101.07
dtype: float64

In [15]:
df[["Temp_C", "Dew_Point", "Relative_Humidity", "Wind_Speed", "Visibility", "Pressure"]].mode()

   Temp_C  Dew_Point  Relative_Humidity  Wind_Speed  Visibility  Pressure
0    16.6       -0.9               68.0         9.0        25.0    101.13
1     NaN       12.9                NaN         NaN         NaN       NaN

In [16]:
df[["Temp_C", "Dew_Point", "Relative_Humidity", "Wind_Speed", "Visibility", "Pressure"]].describe()

,Temp_C,Dew_Point,Relative_Humidity,Wind_Speed,Visibility,Pressure
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,8.798144,2.555294,67.431694,14.945469,27.664447,101.051623
std,11.687883,10.883072,16.918881,8.688696,12.622688,0.844005
min,-23.300000,-28.500000,18.000000,0.000000,0.200000,97.520000
25%,0.100000,-5.900000,56.000000,9.000000,24.100000,100.560000
50%,9.300000,3.300000,68.000000,13.000000,25.000000,101.070000
75%,18.800000,11.800000,81.000000,20.000000,25.000000,101.590000
max,33.000000,24.400000,100.000000,83.000000,48.300000,103.650000

In [17]:
#6 -- celsius to fahrenheit
def toF(df):
    fah = []
    for i in range(len(df)):
        fah.append(df["Temp_C"][i])
        fah[i] = round(((df["Temp_C"][i])*(9/5)+32),2)
    return fah

In [18]:
print(toF(df))
TF = toF(df)
df['Temp_F'] = TF

[28.76, 28.76, 28.76, 29.3, 29.3, 29.48, 29.3, 29.48, 29.48, 29.66, 30.2, 31.1, 31.64, 32.36, 33.44, 35.24, 36.68, 37.4, 38.84, 37.58, 37.76, 39.2, 39.92, 41.54, 41.36, 40.28, 39.02, 38.66, 37.22, 36.68, 36.14, 35.6, 35.42, 35.24, 34.7, 35.96, 35.06, 33.98, 33.98, 32.0, 30.74, 28.22, 24.62, 23.36, 21.92, 21.56, 19.4, 18.68, 15.8, 14.54, 13.1, 11.66, 9.32, 8.78, 8.06, 6.8, 5.36, 5.0, 4.46, 5.18, 5.18, 4.82, 5.18, 5.36, 4.46, 3.56, 2.66, 1.58, 0.86, 1.4, 1.22, 0.86, 0.5, -0.22, -0.58, -1.3, -1.3, -1.48, -1.3, -0.76, -0.04, 1.76, 4.64, 6.44, 7.34, 9.68, 11.66, 13.64, 15.08, 15.98, 15.98, 16.88, 17.96, 18.32, 14.9, 14.72, 16.16, 18.5, 22.28, 23.0, 24.62, 19.4, 17.24, 19.22, 21.02, 20.12, 21.2, 21.92, 23.54, 24.08, 22.82, 24.26, 23.0, 19.94, 19.22, 15.44, 14.36, 15.8, 14.18, 15.08, 14.72, 14.0, 13.1, 12.92, 11.66, 10.76, 10.4, 6.08, 9.86, 9.5, 9.86, 10.4, 10.94, 10.58, 11.84, 11.3, 11.12, 11.84, 13.1, 13.1, 13.64, 14.9, 15.26, 15.8, 16.34, 16.7, 17.42, 17.96, 18.5, 19.58, 19.94, 19.4, 20.48, 21.02, 21.74, 22.28, 22.1, 23.36, 24.08, 25.34, 25.52, 26.42, 26.24, 26.6, 28.76, 29.66, 29.3, 32.72, 33.08, 30.92, 28.94, 25.7, 24.08, 21.38, 21.56, 21.92, 21.38, 20.48, 20.3, 19.22, 19.94, 20.3, 20.3, 20.12, 20.12, 19.04, 17.42, 17.6, 17.06, 17.06, 16.34, 15.8, 15.44, 14.36, 15.8, 16.16, 16.7, 16.88, 18.14, 19.76, 21.38, 22.28, 23.36, 25.34, 27.5, 28.94, 29.48, 30.2, 29.66, 29.48, 30.2, 30.02, 29.3, 28.94, 31.46, 31.64, 36.5, 36.14, 34.52, 34.88, 34.16, 33.44, 33.26, 34.7, 34.16, 34.88, 35.6, 36.68, 34.52, 33.26, 31.64, 29.48, 26.42, 24.8, 23.18, 21.74, 20.48, 20.12, 18.86, 16.52, 14.9, 12.74, 10.4, 9.14, 7.88, 6.98, 6.08, 6.08, 5.54, 6.26, 6.98, 7.88, 9.14, 10.04, 11.48, 11.12, 10.76, 10.58, 10.4, 10.76, 11.84, 11.84, 12.56, 12.74, 14.0, 14.36, 15.08, 15.8, 16.7, 17.6, 18.32, 18.86, 19.22, 19.76, 20.84, 21.2, 21.56, 21.56, 21.74, 22.64, 23.18, 22.82, 22.28, 23.0, 23.0, 23.54, 24.62, 23.72, 22.82, 23.0, 23.36, 23.9, 23.0, 22.82, 22.28, 22.82, 22.82, 23.0, 23.36, 23.36, 23.36, 23.18, 23.36, 24.26, 25.34, 26.78, 28.94, 27.5, 26.24, 23.36, 22.1, 18.32, 15.98, 14.54, 11.84, 10.4, 7.88, 6.26, 4.64, 1.76, -0.22, -0.4, -0.4, -0.04, 0.5, 1.22, 1.94, 1.94, 1.94, 0.68, 0.14, -0.94, -3.28, -4.0, -3.82, -4.54, -6.16, -5.98, -6.52, -5.26, -5.8, -6.34, -9.76, -9.04, -9.94, -7.96, -5.08, -2.74, -0.4, 1.76, 3.2, 4.28, 4.82, 2.84, 2.66, 2.66, 1.94, 1.58, 1.58, 1.58, 1.22, -0.04, -1.3, -2.56, -1.66, -2.38, -1.66, -0.22, -0.22, 6.08, 7.52, 9.14, 12.74, 13.82, 15.8, 17.6, 19.22, 18.32, 9.5, 5.36, 6.8, 8.78, 10.04, 11.3, 12.56, 13.28, 14.54, 15.44, 15.8, 17.06, 18.14, 18.5, 18.68, 19.4, 20.3, 21.02, 22.46, 22.82, 24.26, 25.34, 25.7, 25.52, 25.7, 26.06, 25.52, 26.78, 29.12, 30.92, 35.78, 38.66, 32.9, 25.7, 21.02, 18.14, 16.7, 14.36, 12.38, 11.84, 11.84, 12.02, 12.2, 12.92, 13.46, 13.28, 12.92, 11.66, 10.4, 9.14, 7.88, 7.34, 6.44, 5.18, 2.12, 4.64, 6.26, -0.4, 4.28, 2.12, 4.46, 5.72, 7.34, 9.14, 10.94, 12.2, 16.16, 18.86, 19.4, 19.94, 19.94, 19.58, 23.0, 25.52, 25.34, 23.0, 24.44, 24.62, 24.62, 24.62, 24.98, 23.36, 21.2, 20.66, 18.32, 16.52, 13.28, 10.04, 7.34, 6.44, 4.64, 3.56, 4.1, 5.0, 5.36, 4.28, 3.38, 2.66, 1.58, -1.3, -0.58, 0.68, 2.48, 3.02, 4.46, 3.38, 4.46, 5.36, 6.26, 6.98, 6.8, 3.38, 2.66, 3.38, 5.72, 7.88, 9.5, 10.76, 11.12, 10.22, 8.6, 7.88, -1.3, 3.2, 0.32, 0.68, -0.94, 0.5, -1.3, -1.12, 1.04, -3.1, -2.2, -1.48, -1.3, 2.84, 5.9, 8.6, 11.3, 11.84, 15.08, 16.34, 17.6, 14.9, 13.28, 13.28, 9.86, 8.78, 8.24, 8.06, 8.78, 8.78, 8.24, 10.22, 11.84, 14.18, 16.16, 17.42, 19.04, 23.18, 25.52, 34.16, 36.14, 36.5, 36.86, 36.86, 37.58, 37.58, 37.4, 37.76, 37.22, 37.94, 38.48, 39.2, 38.3, 37.58, 37.58, 41.0, 39.56, 38.66, 38.12, 37.22, 37.4, 37.22, 37.4, 37.58, 37.76, 37.04, 36.32, 35.42, 35.06, 34.88, 34.7, 34.7, 34.34, 33.98, 33.98, 33.8, 32.9, 31.82, 31.28, 31.1, 30.74, 28.94, 26.96, 24.98, 23.54, 22.64, 22.46, 22.46, 23.0, 23.54, 23.9, 24.08, 24.08, 23.36, 22.82, 22.28, 23.18, 22.28, 22.1, 22.28, 21.38, 19.4, 17.24, 17.42, 16.7, 15.8, 11.84, 12.92, 15.44, 17.78, 21.74, 23.0, 23.72, 24.8, 25.88, 26.6, 25.16, 24.26, 23.54, 23.9, 23.72, 22.64, 22.46, 21.56, 21.74, 22.1, 22.1, 22.46, 23.18, 24.8, 28.22, 30.56, 32.54, 33.26, 33.08, 33.26, 33.26, 33.26, 32.9, 32.54, 31.46, 30.92, 31.46, 32.18, 30.74, 29.66, 29.3, 29.12, 29.3, 31.64, 32.36, 32.72, 32.18, 32.54, 28.94, 29.84, 28.22, 29.12, 30.02, 30.92, 31.46, 33.62, 34.16, 34.16, 34.52, 34.16, 34.88, 35.96, 35.06, 35.78, 36.14, 34.16, 34.7, 33.62, 32.54, 31.64, 30.38, 29.3, 28.4, 28.58, 28.04, 28.22, 28.76, 30.56, 32.18, 32.9, 32.72, 32.36, 33.26, 30.74, 30.02, 29.12, 28.4, 28.94, 27.86, 25.88, 25.34, 24.08, 22.82, 21.02, 18.14, 17.78, 15.98, 14.36, 13.1, 14.9, 16.16, 18.14, 19.4, 18.5, 19.94, 19.58, 18.86, 18.68, 18.68, 16.16, 14.9, 16.88, 17.96, 16.52, 19.4, 19.22, 20.3, 19.76, 19.22, 19.22, 19.4, 14.72, 14.36, 13.82, 14.54, 15.26, 16.52, 17.06, 16.88, 17.24, 17.6, 18.14, 17.96, 18.14, 18.68, 19.22, 19.22, 19.76, 19.94, 19.94, 19.76, 20.3, 21.56, 21.56, 22.28, 22.1, 22.1, 21.74, 21.74, 21.56, 22.1, 23.0, 23.18, 23.18, 23.9, 24.26, 24.8, 24.98, 25.52, 24.26, 23.0, 23.18, 23.0, 22.1, 20.66, 21.92, 22.1, 22.64, 21.2, 19.58, 18.32, 18.14, 17.24, 17.06, 17.42, 18.68, 19.94, 19.94, 20.12, 19.22, 18.14, 19.4, 15.98, 19.04, 17.6, 19.04, 14.54, 12.2, 13.64, 11.12, 9.32, 11.84, 10.76, 11.66, 12.92, 16.16, 19.76, 20.66, 20.84, 23.36, 25.16, 26.78, 26.06, 25.88, 25.34, 25.16, 24.44, 23.54, 22.46, 25.34, 23.9, 23.9, 24.8, 23.18, 19.22, 17.42, 15.08, 12.2, 11.12, 14.72, 16.88, 18.32, 20.12, 20.66, 21.2, 22.28, 21.74, 20.84, 20.12, 18.14, 16.16, 14.18, 13.46, 13.82, 10.58, 10.22, 6.08, 8.78, 5.18, 6.44, 5.54, 3.74, 5.0, 7.7, 12.02, 13.1, 16.34, 19.04, 22.1, 22.46, 23.54, 24.44, 24.98, 26.42, 26.96, 27.5, 28.22, 29.3, 30.74, 30.56, 32.18, 32.18, 33.44, 33.8, 33.98, 34.16, 33.98, 33.98, 34.52, 35.42, 36.68, 36.68, 37.4, 37.94, 37.94, 37.22, 37.76, 37.58, 36.68, 37.4, 36.86, 35.96, 35.42, 35.24, 34.7, 33.44, 30.2, 28.58, 26.78, 22.1, 21.02, 20.84, 20.84, 21.2, 21.92, 22.64, 22.82, 23.36, 23.0, 21.38, 18.86, 17.24, 15.44, 14.72, 12.56, 10.76, 7.16, 10.58, 10.22, 9.68, 6.8, 9.32, 9.68, 10.94, 12.56, 14.72, 17.24, 20.66, 23.72, 26.06, 27.68, 28.76, 29.12, 28.22, 27.5, 26.24, 26.06, 26.42, 25.52, 25.52, 24.8, 25.88, 24.98, 25.7, 25.88, 24.62, 23.18, 22.28, 23.18, 25.7, 27.5, 29.84, 31.82, 33.26, 34.7, 36.32, 36.86, 35.6, 34.88, 32.72, 32.9, 32.36, 33.44, 32.18, 32.72, 32.18, 32.0, 30.2, 30.56, 30.56, 30.74, 31.1, 30.38, 31.82, 33.62, 34.52, 34.52, 34.34, 33.98, 34.34, 33.8, 33.62, 32.72, 32.0, 31.64, 31.28, 30.74, 30.38, 29.48, 18.68, 16.52, 14.9, 12.56, 11.3, 10.04, 8.6, 7.34, 7.34, 7.88, 8.42, 8.96, 10.22, 11.66, 12.56, 13.28, 13.1, 8.96, 6.8, 6.08, 6.98, 7.7, 5.9, 5.0, 4.46, 3.38, 1.76, 2.12, 2.48, 1.94, 1.94, 1.58, 1.94, 2.12, 3.02, 5.36, 6.98, 8.24, 9.5, 10.4, 10.4, 9.86, 10.58, 11.66, 12.56, 12.92, 13.46, 14.0, 15.08, 16.16, 16.16, 16.88, 17.6, 17.78, 17.78, 17.6, 18.5, 19.76, 20.3, 22.64, 23.18, 24.26, 25.88, 25.88, 25.52, 23.18, 21.92, 19.04, 18.5, 15.8, 12.56, 10.76, 10.58, 8.78, 8.24, 7.88, 7.88, 6.44, 7.34, 7.52, 11.12, 16.16, 23.0, 26.24, 28.22, 32.18, 33.98, 36.14, 33.98, 34.34, 35.24, 31.64, 30.92, 31.1, 29.84, 28.58, 28.76, 29.84, 29.12, 30.74, 29.66, 30.2, 31.46, 32.18, 33.08, 33.8, 35.6, 35.78, 35.06, 34.7, 35.42, 35.96, 35.78, 34.7, 34.7, 34.7, 34.34, 34.16, 34.52, 33.44, 33.98, 33.26, 33.26, 33.62, 33.26, 34.34, 35.06, 34.16, 35.24, 36.86, 37.94, 38.48, 37.94, 38.3, 38.48, 38.66, 38.48, 37.4, 36.5, 35.06, 34.7, 34.7, 34.34, 34.34, 34.34, 34.34, 34.52, 36.14, 37.04, 37.4, 37.4, 37.04, 36.14, 36.5, 36.68, 36.68, 37.4, 38.3, 37.4, 37.58, 36.68, 36.14, 35.6, 35.24, 35.06, 34.16, 33.62, 33.26, 33.26, 32.54, 32.54, 31.46, 30.92, 31.64, 30.92, 30.92, 30.92, 32.18, 32.9, 33.98, 35.24, 34.16, 34.7, 34.7, 33.8, 33.44, 30.92, 28.94, 27.68, 25.7, 24.98, 24.98, 23.9, 22.64, 21.2, 21.56, 21.38, 19.94, 20.66, 21.56, 22.64, 23.54, 24.8, 26.24, 27.14, 27.86, 29.12, 29.12, 28.22, 26.78, 26.24, 25.16, 23.36, 22.28, 20.66, 19.94, 18.32, 16.16, 16.16, 14.36, 13.64, 12.74, 12.2, 14.18, 16.34, 17.6, 19.22, 21.2, 23.54, 26.42, 28.4, 28.76, 28.58, 26.24, 25.52, 24.8, 25.7, 26.06, 21.56, 24.8, 24.26, 24.62, 22.46, 22.64, 21.02, 21.02, 20.84, 23.0, 26.42, 29.48, 31.82, 32.0, 33.8, 35.42, 35.96, 35.6, 35.96, 35.42, 35.78, 31.64, 31.1, 30.92, 32.9, 32.9, 33.44, 34.52, 34.34, 34.16, 34.52, 34.7, 34.88, 36.68, 37.22, 39.2, 40.28, 41.36, 42.44, 42.98, 41.72, 37.22, 36.68, 36.32, 35.42, 34.88, 36.14, 36.86, 36.68, 36.14, 35.06, 33.98, 33.08, 32.9, 32.72, 32.9, 33.08, 32.72, 33.98, 34.88, 36.14, 35.78, 35.78, 34.52, 35.42, 36.86, 36.14, 34.88, 34.88, 33.98, 32.9, 31.64, 30.2, 30.38, 28.94, 28.76, 25.16, 26.96, 26.42, 26.6, 29.66, 30.74, 32.54, 33.26, 33.62, 33.98, 33.8, 33.98, 33.8, 31.82, 31.82, 32.0, 32.0, 32.0, 32.54, 33.08, 33.44, 33.8, 33.44, 32.72, 33.26, 32.72, 33.08, 32.0, 29.48, 28.76, 29.48, 28.94, 28.22, 27.5, 27.14, 26.24, 26.06, 25.52, 26.24, 25.52, 23.54, 22.46, 21.92, 20.12, 18.32, 17.06, 15.8, 15.44, 14.18, 12.56, 11.12, 11.66, 10.22, 10.22, 11.12, 11.84, 13.82, 15.26, 17.06, 18.32, 19.22, 19.76, 18.32, 17.78, 17.96, 17.78, 16.7, 16.52, 14.9, 17.24, 16.52, 16.7, 17.06, 17.24, 16.88, 15.8, 15.08, 14.36, 15.08, 16.34, 16.34, 20.66, 23.18, 22.1, 22.82, 23.18, 22.64, 20.66, 19.22, 19.04, 18.86, 19.22, 19.76, 19.94, 20.3, 20.12, 21.38, 22.1, 22.28, 19.58, 17.42, 16.88, 17.06, 18.5, 20.3, 21.56, 22.1, 23.36, 24.44, 24.26, 24.08, 22.46, 21.38, 19.76, 16.34, 17.06, 14.0, 17.24, 14.9, 14.54, 11.3, 13.46, 8.42, 10.04, 10.94, 12.92, 16.7, 20.12, 23.54, 24.98, 26.78, 26.78, 26.42, 25.52, 24.62, 23.54, 23.72, 23.9, 23.72, 23.9, 22.82, 22.1, 21.74, 22.28, 23.54, 22.28, 22.46, 22.64, 23.18, 23.0, 23.18, 23.54, 24.08, 24.26, 24.26, 24.98, 26.06, 27.14, 26.78, 26.6, 25.52, 25.34, 24.98, 24.26, 24.26, 23.36, 22.46, 22.64, 22.1, 21.92, 22.1, 21.92, 21.74, 21.74, 21.02, 21.38, 22.1, 22.64, 23.72, 24.62, 26.06, 26.78, 27.14, 27.68, 28.76, 27.86, 29.48, 32.36, 32.9, 33.8, 34.16, 30.92, 31.46, 32.54, 33.44, 34.7, 35.6, 36.86, 37.4, 38.66, 39.2, 41.36, 42.44, 43.7, 41.54, 41.0, 39.74, 38.66, 38.12, 37.76, 37.22, 37.04, 36.14, 32.9, 30.56, 28.76, 28.22, 26.78, 24.26, 23.36, 21.74, 21.38, 20.66, 20.66, 20.3, 21.56, 22.1, 21.74, 21.92, 22.1, 19.58, 17.78, 17.78, 16.7, 15.8, 13.82, 12.02, 9.68, 7.52, 5.9, 5.0, 4.1, 3.38, 2.84, 2.84, 3.74, 4.82, 6.08, 7.88, 10.04, 11.66, 12.56, 14.0, 14.18, 14.9, 14.36, 13.82, 13.1, 12.2, 11.12, 9.32, 7.88, 7.88, 7.34, 5.36, 5.9, 5.72, 4.46, 5.36, 8.6, 11.66, 14.0, 15.8, 17.96, 19.94, 21.56, 22.46, 23.18, 23.36, 20.66, 22.28, 22.46, 22.28, 23.0, 23.9, 25.52, 24.98, 21.74, 22.46, 22.64, 22.46, 24.26, 24.98, 23.72, 27.5, 31.82, 37.4, 43.52, 48.02, 48.74, 49.46, 52.52, 49.82, 41.9, 42.8, 45.68, 44.24, 42.8, 40.64, 43.16, 41.9, 46.22, 50.18, 50.0, 42.26, 45.68, 50.54, 44.06, 50.36, 53.78, 54.86, 53.06, 52.7, 53.06, 53.06, 52.88, 52.34, 50.9, 42.98, 41.0, 38.66, 35.6, 33.44, 31.82, 32.0, 29.84, 27.32, 24.98, 24.98, 24.26, 23.0, 23.54, 24.8, 25.34, 26.6, 28.22, 29.3, 30.2, 30.02, 30.74, 30.38, 28.4, 27.32, 28.4, 28.58, 28.04, 27.32, 28.04, 27.14, 25.16, 24.62, 21.74, 20.48, 19.76, 19.22, 19.76, 20.66, 21.02, 24.8, 24.62, 26.24, 27.32, 27.14, 28.76, 29.12, 28.22, 28.58, 27.86, 27.86, 28.4, 28.94, 26.42, 26.24, 26.42, 28.04, 28.94, 28.22, 29.3, 28.76, 32.18, 36.86, 38.84, 42.62, 44.24, 48.2, 49.1, 50.9, 51.62, 51.26, 48.38, 45.32, 40.64, 40.64, 41.36, 42.98, 42.8, 41.36, 40.28, 34.7, 35.24, 36.14, 37.58, 36.68, 39.92, 43.7, 46.94, 51.08, 51.44, 52.88, 54.14, 54.32, 53.24, 52.88, 48.2, 47.66, 48.56, 47.12, 46.22, 43.88, 45.5, 41.18, 40.64, 40.28, 43.7, 42.44, 45.32, 39.2, 41.9, 39.92, 38.3, 38.3, 39.02, 40.82, 43.7, 41.54, 41.9, 40.82, 39.2, 37.58, 36.68, 33.98, 34.52, 33.98, 33.26, 33.26, 33.08, 33.44, 33.44, 33.26, 33.08, 33.44, 33.98, 34.88, 33.98, 32.72, 33.8, 35.78, 35.96, 35.06, 34.7, 33.8, 32.9, 32.54, 32.36, 31.82, 31.46, 30.92, 30.92, 30.92, 31.28, 31.46, 31.64, 31.46, 31.46, 31.1, 31.1, 31.46, 32.72, 33.98, 35.96, 38.12, 38.12, 39.2, 38.3, 37.4, 36.68, 36.32, 36.14, 35.6, 35.78, 35.24, 35.24, 35.42, 33.98, 33.98, 33.8, 33.26, 33.08, 33.98, 33.98, 33.98, 34.7, 35.24, 36.5, 37.94, 39.2, 38.66, 39.74, 39.38, 38.84, 38.84, 38.66, 39.2, 38.84, 38.66, 38.84, 37.4, 36.86, 35.24, 32.54, 31.82, 31.82, 32.9, 33.8, 34.88, 36.68, 39.38, 42.26, 46.58, 48.56, 50.36, 50.9, 50.18, 50.18, 49.64, 48.74, 47.84, 45.86, 44.06, 38.84, 41.36, 39.74, 39.02, 37.76, 38.3, 38.48, 41.18, 47.84, 50.72, 53.42, 57.38, 63.14, 68.0, 71.06, 71.96, 72.86, 71.24, 65.12, 62.78, 55.04, 56.12, 54.68, 51.08, 49.64, 51.44, 51.08, 50.36, 52.16, 49.46, 52.34, 49.82, 53.42, 57.02, 60.08, 64.04, 67.64, 65.3, 62.6, 61.34, 61.88, 60.62, 57.02, 54.5, 51.08, 49.1, 47.84, 44.96, 44.78, 42.98, 42.26, 41.36, 41.36, 41.0, 37.76, 41.9, 46.4, 51.08, 54.68, 58.82, 61.7, 68.0, 70.7, 72.5, 73.94, 71.6, 67.46, 63.5, 64.58, 60.8, 57.56, 57.74, 57.2, 54.32, 53.24, 52.52, 51.08, 50.0, 49.1, 52.34, 56.84, 60.62, 64.76, 68.36, 72.14, 74.84, 76.46, 77.72, 77.9, 77.36, 69.26, 62.96, 65.12, 61.52, 64.4, 61.7, 62.6, 59.9, 59.0, 51.8, 55.76, 55.04, 56.66, 57.56, 59.72, 63.14, 67.28, 68.72, 73.4, 73.94, 73.04, 70.52, 71.96, 68.0, 64.76, 62.06, 59.18, 53.78, 51.8, 52.34, 50.72, 50.54, 48.02, 47.84, 48.56, 46.4, 43.88, 47.12, 52.34, 55.04, 58.1, 58.82, 61.16, 62.24, 61.88, 61.52, 59.9, 58.46, 56.12, 53.24, 51.62, 51.44, 51.08, 49.82, 47.12, 45.14, 43.16, 41.54, 39.92, 38.48, 37.76, 37.58, 36.86, 37.4, 38.66, 38.66, 40.64, 40.46, 42.98, 42.44, 42.98, 42.98, 42.98, 43.16, 43.34, 43.88, 43.88, 43.7, 42.44, 42.62, 42.62, 42.44, 41.54, 40.1, 38.84, 36.5, 37.4, 37.58, 39.02, 41.36, 42.62, 43.88, 45.5, 45.68, 47.12, 48.56, 48.02, 47.66, 45.14, 46.76, 45.5, 43.52, 45.14, 40.28, 36.68, 33.44, 30.02, 28.58, 25.16, 25.16, 24.8, 26.6, 28.22, 30.92, 32.36, 33.08, 34.34, 34.52, 34.34, 34.16, 32.18, 30.74, 29.48, 27.86, 26.78, 25.52, 24.26, 23.0, 22.28, 21.2, 20.3, 18.68, 18.5, 21.02, 22.82, 24.26, 27.5, 29.12, 32.36, 33.8, 35.06, 35.78, 36.86, 36.86, 36.68, 37.04, 36.68, 35.78, 33.8, 33.8, 33.8, 30.02, 30.2, 29.12, 29.3, 30.2, 31.46, 32.9, 33.44, 35.78, 36.14, 37.04, 38.84, 39.74, 39.92, 36.5, 35.96, 34.7, 34.34, 34.34, 34.16, 33.8, 33.8, 33.44, 33.08, 32.9, 32.72, 32.9, 33.08, 33.08, 33.26, 33.44, 34.7, 36.5, 37.76, 38.48, 39.02, 39.56, 39.2, 39.38, 39.02, 38.3, 38.12, 37.22, 35.96, 35.42, 34.52, 33.44, 32.18, 30.2, 28.04, 25.7, 24.26, 22.82, 23.36, 24.26, 26.6, 28.4, 30.56, 33.62, 34.88, 37.58, 39.92, 40.64, 40.64, 39.92, 39.02, 37.58, 37.4, 35.06, 32.72, 34.52, 34.7, 34.34, 34.34, 33.26, 30.38, 30.92, 31.1, 31.46, 33.26, 34.7, 37.22, 40.28, 43.52, 43.7, 45.86, 45.86, 47.12, 46.22, 44.6, 42.62, 39.92, 36.68, 36.86, 34.7, 32.72, 29.3, 32.18, 30.2, 30.2, 31.28, 32.9, 34.16, 37.76, 38.66, 39.38, 40.64, 42.44, 42.62, 40.46, 38.84, 37.4, 37.04, 36.5, 36.68, 36.68, 36.68, 36.5, 35.6, 32.72, 31.82, 31.28, 29.48, 29.84, 28.94, 28.76, 32.36, 35.78, 38.12, 40.1, 40.28, 43.16, 44.06, 45.14, 46.22, 46.22, 46.4, 44.42, 40.82, 38.3, 37.58, 33.08, 33.8, 31.46, 30.02, 30.38, 26.6, 28.22, 27.32, 28.4, 32.54, 35.06, 36.5, 39.74, 43.52, 44.78, 47.66, 50.0, 51.62, 51.44, 49.46, 48.02, 47.12, 46.04, 44.78, 44.42, 44.42, 42.8, 42.08, 42.8, 41.72, 41.36, 40.28, 39.56, 40.64, 41.9, 43.7, 47.66, 48.74, 48.02, 47.66, 47.3, 46.4, 46.94, 46.58, 45.68, 43.7, 42.8, 40.82, 38.66, 38.48, 37.76, 36.14, 36.14, 35.42, 34.7, 34.7, 34.7, 36.14, 36.86, 39.02, 40.1, 40.64, 41.36, 43.88, 44.06, 45.68, 48.02, 45.86, 43.88, 42.08, 41.54, 40.82, 39.92, 38.3, 37.4, 37.04, 36.14, 34.7, 33.98, 31.82, 31.1, 32.72, 33.98, 35.78, 39.02, 42.26, 43.88, 45.68, 47.48, 48.74, 47.3, 45.86, 45.14, 45.14, 44.06, 44.06, 44.24, 42.98, 42.08, 41.9, 37.58, 36.32, 36.5, 32.36, 34.7, 36.32, 40.1, 40.1, 42.26, 42.8, 43.88, 44.24, 46.04, 46.4, 47.12, 47.12, 46.4, 46.4, 45.86, 45.5, 43.16, 42.62, 42.44, 40.64, 39.56, 38.66, 38.66, 39.2, 40.64, 42.26, 43.88, 45.32, 45.14, 48.92, 50.72, 53.06, 53.78, 54.14, 54.32, 54.14, 53.42, 52.7, 51.62, 50.72, 50.36, 47.3, 45.5, 40.64, 41.72, 41.9, 42.26, 42.62, 42.98, 43.34, 43.88, 45.32, 44.6, 45.32, 46.22, 47.84, 48.2, 47.48, 47.66, 46.94, 43.16, 43.52, 42.26, 42.44, 41.72, 41.54, 41.18, 40.82, 40.28, 39.74, 39.2, 39.2, 39.74, 41.0, 41.54, 42.26, 44.42, 44.42, 46.4, 47.84, 45.68, 43.16, 44.06, 44.24, 42.8, 42.44, 41.36, 41.18, 39.92, 40.46, 39.74, 39.2, 37.76, 37.4, 34.88, 33.26, 36.32, 37.76, 40.28, 42.98, 44.06, 44.06, 47.84, 51.8, 47.12, 45.5, 49.1, 48.74, 47.12, 43.52, 45.32, 44.42, 37.94, 43.88, 41.9, 42.44, 40.64, 39.74, 37.58, 38.84, 38.3, 39.2, 43.7, 45.86, 47.66, 49.64, 50.72, 50.0, 50.54, 52.34, 54.32, 52.52, 52.34, 49.82, 48.38, 43.88, 44.06, 42.62, 40.28, 39.2, 35.6, 34.7, 34.16, 34.34, 35.24, 39.38, 42.98, 46.4, 49.64, 53.96, 56.3, 58.46, 59.0, 60.62, 60.98, 59.0, 57.74, 56.48, 53.96, 53.06, 50.54, 48.38, 46.22, 45.5, 44.24, 41.72, 42.26, 43.16, 44.06, 45.5, 48.56, 51.44, 55.04, 56.84, 59.54, 58.64, 58.46, 60.08, 60.62, 59.72, 58.1, 53.42, 55.04, 53.6, 51.8, 52.88, 55.22, 55.58, 54.32, 52.34, 51.62, 49.82, 51.08, 53.06, 56.3, 57.38, 59.9, 63.14, 65.12, 67.64, 66.92, 64.58, 63.5, 62.6, 61.88, 61.34, 59.9, 58.28, 58.64, 58.82, 60.26, 58.28, 58.82, 57.92, 59.36, 59.54, 60.26, 62.6, 66.74, 71.96, 76.82, 75.38, 76.64, 77.72, 79.88, 81.32, 82.04, 81.14, 80.06, 79.52, 68.9, 66.74, 66.92, 67.1, 66.2, 66.02, 63.32, 59.72, 58.1, 56.3, 53.42, 51.62, 50.36, 50.36, 51.62, 52.7, 53.6, 53.96, 54.68, 54.86, 52.88, 51.98, 49.1, 47.3, 45.32, 42.98, 41.72, 39.02, 37.22, 36.32, 33.62, 33.98, 32.72, 30.2, 33.62, 36.5, 37.94, 40.1, 41.54, 44.42, 45.14, 47.48, 48.74, 50.72, 50.54, 50.36, 50.0, 47.12, 45.68, 46.22, 47.12, 44.24, 43.7, 41.9, 37.94, 39.92, 38.12, 38.12, 40.46, 44.78, 47.48, 53.24, 57.2, 60.44, 61.88, 65.12, 66.74, 68.36, 69.26, 68.0, 65.66, 64.4, 61.88, 60.98, 57.02, 54.68, 54.5, 51.62, 49.82, 48.38, 47.84, 47.66, 46.04, 44.42, 42.98, 43.34, 43.88, 44.42, 44.96, 45.5, 49.28, 49.1, 47.12, 46.04, 45.32, 44.6, 44.42, 43.88, 43.7, 43.88, 43.34, 43.52, 42.26, 41.9, 42.26, 42.8, 43.16, 43.52, 43.16, 41.9, 41.9, 42.08, 41.9, 42.98, 42.98, 42.26, 41.54, 40.64, 38.84, 38.12, 36.68, 36.68, 35.42, 34.88, 34.7, 34.52, 33.08, 33.44, 34.16, 35.24, 35.42, 36.32, 37.04, 37.94, 39.2, 40.28, 41.0, 41.36, 42.62, 42.8, 43.52, 43.34, 43.7, 42.98, 41.54, 39.74, 37.04, 35.6, 35.42, 33.98, 33.98, 35.06, 35.6, 35.42, 35.78, 36.14, 37.04, 37.58, 38.66, 39.38, 40.28, 41.0, 41.54, 42.26, 42.08, 42.62, 42.62, 41.72, 42.26, 42.08, 41.9, 42.08, 42.26, 44.06, 42.98, 44.6, 45.5, 44.78, 44.24, 41.9, 43.88, 45.86, 44.96, 47.84, 48.02, 46.4, 46.4, 47.12, 46.58, 46.4, 45.86, 44.78, 44.42, 43.88, 42.8, 41.72, 40.82, 41.9, 40.1, 39.92, 40.64, 40.1, 41.36, 41.9, 40.82, 41.18, 42.98, 46.04, 46.4, 47.66, 49.64, 45.86, 47.84, 47.84, 46.4, 45.14, 45.14, 44.6, 43.16, 42.8, 42.44, 40.82, 38.66, 38.3, 36.86, 36.68, 37.76, 41.9, 43.16, 44.42, 47.84, 49.28, 49.64, 50.54, 51.8, 52.16, 52.52, 51.8, 47.48, 46.94, 46.58, 46.4, 45.68, 44.42, 42.44, 40.64, 40.46, 39.92, 39.56, 37.94, 36.5, 35.24, 36.14, 36.86, 38.66, 37.4, 36.86, 36.86, 35.42, 36.5, 35.78, 35.06, 33.8, 33.26, 32.9, 32.36, 32.36, 32.54, 32.36, 31.64, 31.28, 30.56, 29.66, 29.3, 28.22, 29.66, 31.28, 33.08, 35.6, 39.02, 41.0, 41.72, 43.52, 44.96, 45.32, 45.86, 44.96, 42.98, 39.38, 36.14, 35.42, 33.44, 33.44, 34.34, 34.34, 33.44, 31.82, 33.62, 34.16, 35.24, 36.68, 39.74, 41.9, 43.16, 45.32, 47.12, 47.66, 48.2, 48.56, 48.2, 46.58, 44.42, 43.34, 41.72, 41.18, 39.38, 37.94, 35.96, 37.76, 36.32, 33.26, 30.74, 37.4, 42.8, 43.88, 44.96, 45.68, 48.74, 50.18, 54.32, 54.32, 54.5, 55.22, 54.86, 54.5, 53.96, 53.78, 53.96, 53.6, 51.98, 52.52, 51.44, 49.46, 47.84, 47.12, 46.04, 46.04, 46.22, 46.4, 47.12, 48.56, 49.1, 51.62, 51.08, 51.8, 50.72, 49.82, 50.0, 49.46, 49.28, 48.74, 48.56, 48.38, 48.38, 48.2, 47.48, 47.84, 47.84, 47.48, 47.12, 47.48, 47.12, 47.12, 48.02, 49.1, 50.54, 52.16, 53.24, 55.4, 57.2, 58.82, 59.72, 59.72, 59.36, 57.56, 57.56, 56.3, 53.42, 52.88, 52.52, 52.52, 52.16, 51.98, 51.8, 52.52, 53.06, 54.32, 56.48, 57.56, 59.72, 60.26, 60.62, 61.16, 61.16, 61.7, 61.52, 60.44, 60.26, 59.18, 57.56, 56.84, 56.84, 56.3, 5

In [19]:
#7 -- rename columns
df=df[['Date_Time', 'Temp_C', 'Temp_F','Dew_Point', 'Relative_Humidity', 'Wind_Speed', 'Visibility', 'Pressure', 'Weather']]

In [20]:
df

,Date_Time,Temp_C,Temp_F,Dew_Point,Relative_Humidity,Wind_Speed,Visibility,Pressure,Weather
0,2012-01-01 00:00:00,-1.8,28.76,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,28.76,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,28.76,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,29.30,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,29.30,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,32.18,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,32.36,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,31.10,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,31.64,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,32.00,-2.1,86,30,11.3,99.89,Snow

In [21]:
#8 -- check datatypes
df.dtypes

Date_Time             object
Temp_C               float64
Temp_F               float64
Dew_Point            float64
Relative_Humidity      int64
Wind_Speed             int64
Visibility           float64
Pressure             float64
Weather               object
dtype: object

In [22]:
#9 -- convert Date_Time to datetime64
df.Date_Time = pd.to_datetime(df.Date_Time)

In [23]:
df.dtypes

Date_Time            datetime64[ns]
Temp_C                      float64
Temp_F                      float64
Dew_Point                   float64
Relative_Humidity             int64
Wind_Speed                    int64
Visibility                  float64
Pressure                    float64
Weather                      object
dtype: object

In [71]:
#10 and 11 -- monthly f-temp and rearrange
month=df.Date_Time.dt.month
average=round(df.groupby(month).Temp_F.mean(),2)
monthly_avg=pd.DataFrame({'Temp_F':average})
monthly_avg

           Temp_F
Date_Time
1           18.73
2           24.39
3           37.62
4           44.62
5           61.23
6           68.24
7           73.02
8           72.10
9           61.67
10          51.72
11          33.68
12          26.05

In [72]:
#12 -- Rename Index to month
monthly_avg.index.rename('Month', True)
monthly_avg

       Temp_F
Month
1       18.73
2       24.39
3       37.62
4       44.62
5       61.23
6       68.24
7       73.02
8       72.10
9       61.67
10      51.72
11      33.68
12      26.05

In [146]:
#13 -- Remove index name
monthly_avg.index.rename('Month', True)
monthly_avg

AttributeError: can't delete attribute

In [148]:
#14 -- monthly_avg: month name instead of number, no brute force :(((

month_dict = { 1: 'January',
               2: 'February',
               3: 'March',
               4: 'April',
               5: 'May',
               6: 'June',
               7: 'July',
               8: 'August',
               9: 'September',
               10: 'October',
               11: 'November',
               12: 'December'
            }
monthly_avg.index = list(map(lambda x: month_dict[x], monthly_avg.index))
monthly_avg

           Temp_F
January     18.73
February    24.39
March       37.62
April       44.62
May         61.23
June        68.24
July        73.02
August      72.10
September   61.67
October     51.72
November    33.68
December    26.05

In [125]:
#15 -- Hourly Average
hour = df.Date_Time.dt.hour
average = round(df.groupby(hour).Temp_F.mean(),2)
hourly_avg = pd.Series(average)
hourly_avg.to_frame()

           Temp_F
Date_Time
0           45.62
1           44.76
2           43.98
3           43.33
4           42.74
5           42.29
6           42.86
7           43.83
8           45.28
9           46.99
10          48.70
11          50.19
12          51.54
13          52.51
14          53.20
15          53.39
16          53.18
17          52.30
18          51.18
19          50.04
20          48.85
21          47.85
22          47.06
23          46.40

In [128]:
#16 -- hourly_avg.index.name = 'Hour'
hourly_avg

Hour
12:00AM    45.62
1:00AM     44.76
2:00AM     43.98
3:00AM     43.33
4:00AM     42.74
5:00AM     42.29
6:00AM     42.86
7:00AM     43.83
8:00AM     45.28
9:00AM     46.99
10:00AM    48.70
11:00AM    50.19
12:00PM    51.54
1:00PM     52.51
2:00PM     53.20
3:00PM     53.39
4:00PM     53.18
5:00PM     52.30
6:00PM     51.18
7:00PM     50.04
8:00PM     48.85
9:00PM     47.85
10:00PM    47.06
11:00PM    46.40
Name: Temp_F, dtype: float64

In [126]:
hourly_avg.to_frame()

           Temp_F
Date_Time
0           45.62
1           44.76
2           43.98
3           43.33
4           42.74
5           42.29
6           42.86
7           43.83
8           45.28
9           46.99
10          48.70
11          50.19
12          51.54
13          52.51
14          53.20
15          53.39
16          53.18
17          52.30
18          51.18
19          50.04
20          48.85
21          47.85
22          47.06
23          46.40

In [127]:
#17 -- hourly dict replacement
hour_dict = {  0: '12:00AM',
               1: '1:00AM',
               2: '2:00AM',
               3: '3:00AM',
               4: '4:00AM',
               5: '5:00AM',
               6: '6:00AM',
               7: '7:00AM',
               8: '8:00AM',
               9: '9:00AM',
               10: '10:00AM',
               11: '11:00AM',
               12: '12:00PM',
               13: '1:00PM',
               14: '2:00PM',
               15: '3:00PM',
               16: '4:00PM',
               17: '5:00PM',
               18: '6:00PM',
               19: '7:00PM',
               20: '8:00PM',
               21: '9:00PM',
               22: '10:00PM',
               23: '11:00PM'
             }
hourly_avg.index = list(map(lambda x: hour_dict[x], hourly_avg.index))
hourly_avg.to_frame()

         Temp_F
12:00AM   45.62
1:00AM    44.76
2:00AM    43.98
3:00AM    43.33
4:00AM    42.74
5:00AM    42.29
6:00AM    42.86
7:00AM    43.83
8:00AM    45.28
9:00AM    46.99
10:00AM   48.70
11:00AM   50.19
12:00PM   51.54
1:00PM    52.51
2:00PM    53.20
3:00PM    53.39
4:00PM    53.18
5:00PM    52.30
6:00PM    51.18
7:00PM    50.04
8:00PM    48.85
9:00PM    47.85
10:00PM   47.06
11:00PM   46.40

In [130]:
#18 -- universe of weather types
df['Weather'].value_counts()

Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                              7
Snow,Ice Pellets                              6
Freezing Drizzle,Fog                          6
Snow,Haze                                     5
Snow Showers,Fog                              4
Moderate Snow                                 4
Freezing Fog                                  4
Freezing Rain,Fog                             4
Rain,Snow,Ice Pellets                         4
Thunderstorms,Rain                            3
Thunderstorms,Rain Showers,Fog                3
Freezing Drizzle,Haze                         3
Rain,Haze                                     3
Drizzle,Snow                                  2
Thunderstorms                                 2
Rain Showers,Snow Showers                     2
Moderate Snow,Blowing Snow                    2
Freezing Rain,Haze                            2
Rain,Snow Grains                              1
Rain,Snow,Fog                                 1
Snow Pellets                                  1
Thunderstorms,Heavy Rain Showers              1
Thunderstorms,Moderate Rain Showers,Fog       1
Moderate Rain,Fog                             1
Drizzle,Ice Pellets,Fog                       1
Freezing Rain,Snow Grains                     1
Freezing Rain,Ice Pellets,Fog                 1
Rain,Ice Pellets                              1
Thunderstorms,Rain,Fog                        1
Rain Showers,Fog                              1
Name: Weather, dtype: int64

In [137]:
#19 -- unique weather list
uniques_set = set(df['Weather'])    
uniques_list = list(uniques_set)
print(uniques_list)

['Drizzle,Fog', 'Moderate Snow,Blowing Snow', 'Rain,Snow,Fog', 'Rain Showers,Fog', 'Mostly Cloudy', 'Freezing Rain,Fog', 'Snow Showers,Fog', 'Rain Showers', 'Cloudy', 'Rain,Fog', 'Drizzle,Snow', 'Snow', 'Moderate Rain,Fog', 'Haze', 'Snow Showers', 'Freezing Rain', 'Thunderstorms,Rain Showers', 'Freezing Fog', 'Thunderstorms,Rain,Fog', 'Drizzle,Ice Pellets,Fog', 'Snow,Ice Pellets', 'Drizzle', 'Moderate Snow', 'Fog', 'Snow,Haze', 'Rain,Snow,Ice Pellets', 'Freezing Rain,Haze', 'Thunderstorms,Rain Showers,Fog', 'Thunderstorms', 'Mainly Clear', 'Snow Pellets', 'Drizzle,Snow,Fog', 'Clear', 'Rain,Snow', 'Snow,Blowing Snow', 'Snow,Fog', 'Freezing Drizzle,Fog', 'Rain Showers,Snow Showers', 'Freezing Rain,Ice Pellets,Fog', 'Freezing Rain,Snow Grains', 'Freezing Drizzle,Haze', 'Rain,Snow Grains', 'Thunderstorms,Moderate Rain Showers,Fog', 'Thunderstorms,Rain', 'Rain', 'Rain,Haze', 'Thunderstorms,Heavy Rain Showers', 'Rain,Ice Pellets', 'Freezing Drizzle', 'Freezing Drizzle,Snow']

In [138]:
#20 -- sorted weather universe
sorted(uniques_list)

['Clear',
 'Cloudy',
 'Drizzle',
 'Drizzle,Fog',
 'Drizzle,Ice Pellets,Fog',
 'Drizzle,Snow',
 'Drizzle,Snow,Fog',
 'Fog',
 'Freezing Drizzle',
 'Freezing Drizzle,Fog',
 'Freezing Drizzle,Haze',
 'Freezing Drizzle,Snow',
 'Freezing Fog',
 'Freezing Rain',
 'Freezing Rain,Fog',
 'Freezing Rain,Haze',
 'Freezing Rain,Ice Pellets,Fog',
 'Freezing Rain,Snow Grains',
 'Haze',
 'Mainly Clear',
 'Moderate Rain,Fog',
 'Moderate Snow',
 'Moderate Snow,Blowing Snow',
 'Mostly Cloudy',
 'Rain',
 'Rain Showers',
 'Rain Showers,Fog',
 'Rain Showers,Snow Showers',
 'Rain,Fog',
 'Rain,Haze',
 'Rain,Ice Pellets',
 'Rain,Snow',
 'Rain,Snow Grains',
 'Rain,Snow,Fog',
 'Rain,Snow,Ice Pellets',
 'Snow',
 'Snow Pellets',
 'Snow Showers',
 'Snow Showers,Fog',
 'Snow,Blowing Snow',
 'Snow,Fog',
 'Snow,Haze',
 'Snow,Ice Pellets',
 'Thunderstorms',
 'Thunderstorms,Heavy Rain Showers',
 'Thunderstorms,Moderate Rain Showers,Fog',
 'Thunderstorms,Rain',
 'Thunderstorms,Rain Showers',
 'Thunderstorms,Rain Showers,Fog',
 'Thunderstorms,Rain,Fog']

In [139]:
#21 -- revert to original columns with Temp (F) addition
df.rename(columns = {'Date_Time': 'Date/Time', 
                     'Temp_F':'Temp (F)',
                     'Temp_C': 'Temp (C)', 
                     'Dew_Point': 'Dew Point Temp (C)', 
                     'Relative_Humidity': 'Rel Hum (%)',
                     'Wind_Speed': 'Wind Spd (km/h)', 
                     'Visibility': 'Visibility (km)', 
                     'Pressure': 'Stn Press (kPa)',
                    }, inplace = True)

In [141]:
df.sample(10)

,Date/Time,Temp (C),Temp (F),Dew Point Temp (C),Rel Hum (%),Wind Spd (km/h),Visibility (km),Stn Press (kPa),Weather
5900,2012-09-02 20:00:00,21.2,70.16,8.5,44,9,25.0,101.52,Clear
5977,2012-09-06 01:00:00,21.0,69.80,18.4,85,7,25.0,100.55,Mostly Cloudy
8488,2012-12-19 16:00:00,1.3,34.34,-0.4,88,7,24.1,100.96,Cloudy
7222,2012-10-27 22:00:00,12.8,55.04,7.8,72,13,25.0,101.13,Mostly Cloudy
3897,2012-06-11 09:00:00,22.4,72.32,15.6,65,7,24.1,101.63,Mostly Cloudy
600,2012-01-26 00:00:00,-5.9,21.38,-11.7,64,6,25.0,101.99,Mostly Cloudy
1511,2012-03-03 23:00:00,2.3,36.14,-3.1,67,33,25.0,99.18,Snow
4716,2012-07-15 12:00:00,29.4,84.92,19.7,56,9,48.3,101.06,Cloudy
1695,2012-03-11 15:00:00,10.5,50.90,-1.3,44,20,48.3,101.69,Clear
6294,2012-09-19 06:00:00,8.0,46.40,4.2,77,26,24.1,100.79,Cloudy

In [149]:
#22
df.to_csv('weather_2012_new.csv', index=False, header = False)

In [150]:
#23
monthly_avg.to_csv('monthly_avg.csv')
hourly_avg.to_csv('hourly_avg.csv')